- name: This is first yml script
  hosts: all
  tasks: 
    - name: This is first task
      ansible.builtin.debug:
         msg: Hello from 1st task

- name: Loops sample examples 
  hosts: all 
  tasks:  
    - name: print course name 
      debug: 
        msg: Course Name is {{item}}
      loop:   
        - aws
        - gcp 
        - azure 


    
    
    


