- name: This is first yml script
  hosts: all
  tasks: 
    - name: Installing NGINX
      debug:
         msg: Hello from 1st task
         
- name: Working on loop
  hosts: all
  tasks: 
    - name: Looping values
      debug:
        msg: Course name is {{item}}
      loop:
          - aws
          - gcp
          - azure


    
    
    


