- name: Installing Nginx
  hosts: all
  become: true

  tasks:
    - name: ensure nginx is at the latest version
      yum:
       name: nginx
       state: latest
      when: ansible_distribution == "Ubuntu"
    - name: start nginx
      service:
          name: nginx
          state: started
